# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
        args: ["--maxkb=2000"]

  # Using this mirror lets us use mypyc-compiled black, which is about 2x faster
-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.8.0
    hooks:
    - id: black
      language_version: python3.12
